/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ActivityPoint: typeof import('./src/components/CommunityFeature/ActivityPoint.vue')['default']
    AdItem: typeof import('./src/components/CommunityFeature/advertisement/adItem.vue')['default']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATimeline: typeof import('ant-design-vue/es')['Timeline']
    ATimelineItem: typeof import('ant-design-vue/es')['TimelineItem']
    AvatarList: typeof import('./src/components/avatar/AvatarList.vue')['default']
    BarChart: typeof import('./src/components/chart/BarChart.vue')['default']
    BlankView: typeof import('./src/components/layout/BlankView.vue')['default']
    ChatBubble: typeof import('./src/components/BasicFeature/ChatBubble.vue')['default']
    ChatScreen: typeof import('./src/components/BasicFeature/ChatScreen.vue')['default']
    CommentsList: typeof import('./src/components/CommunityFeature/CommentsList.vue')['default']
    CommonView: typeof import('./src/components/layout/CommonView.vue')['default']
    DayNightSwitch: typeof import('./src/components/switch/DayNightSwitch.vue')['default']
    EditableCell: typeof import('./src/components/editable-cell/EditableCell.vue')['default']
    FrontView: typeof import('./src/components/layout/FrontView.vue')['default']
    Fullscreen: typeof import('./src/components/fullscreen/Fullscreen.vue')['default']
    GridList: typeof import('./src/components/list/GridList.vue')['default']
    Guider: typeof import('./src/components/guider/Guider.vue')['default']
    HeaderActions: typeof import('./src/components/layout/HeaderActions.vue')['default']
    IconSelector: typeof import('./src/components/selector/IconSelector.vue')['default']
    JumpSquare: typeof import('./src/components/loaders/JumpSquare.vue')['default']
    LineChart: typeof import('./src/components/chart/LineChart.vue')['default']
    LinkView: typeof import('./src/components/layout/LinkView.vue')['default']
    MatrixLoader: typeof import('./src/components/loaders/MatrixLoader.vue')['default']
    MessageInput: typeof import('./src/components/BasicFeature/MessageInput.vue')['default']
    MiniStatisticCard: typeof import('./src/components/statistic/MiniStatisticCard.vue')['default']
    Notice: typeof import('./src/components/notice/Notice.vue')['default']
    OverviewTitle: typeof import('./src/components/statistic/OverviewTitle.vue')['default']
    PageFooter: typeof import('./src/components/layout/PageFooter.vue')['default']
    QandAList: typeof import('./src/components/CommunityFeature/QandAList.vue')['default']
    ReadingLoader: typeof import('./src/components/loaders/ReadingLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/setting/Setting.vue')['default']
    Splitter: typeof import('./src/components/format/Splitter.vue')['default']
  }
}
