ALTER TABLE API_ACCESS_LOGS DROP CONSTRAINT API_ACCESS_LOGS_PK;

ALTER TABLE API_ACCESS_LOGS DROP COLUMN ACCESS_ID;

ALTER TABLE API_ACCESS_LOGS
    ADD ACCESS_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;