ALTER TABLE RECOMMENDATION_LOGS DROP CONSTRAINT RECOMMENDATION_LOGS_PK;

ALTER TABLE RECOMMENDATION_LOGS DROP COLUMN LOG_ID;

ALTER TABLE RECOMMENDATION_LOGS
    ADD LOG_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

ALTER TABLE RECOMMENDATION_LOGS
    ADD CONSTRAINT FK_RECOMMENDATION_LOGS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);