ALTER TABLE SECURITY_EVENTS DROP CONSTRAINT SECURITY_EVENTS_PK;

ALTER TABLE SECURITY_EVENTS DROP COLUMN ENENT_ID;

ALTER TABLE SECURITY_EVENTS
    ADD EVENT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;
