ALTER TABLE SYSTEM_LOGS DROP CONSTRAINT SYSTEM_LOGS_PK;

ALTER TABLE SYSTEM_LOGS DROP COLUMN SYSTEM_LOG_ID;

ALTER TABLE SYSTEM_LOGS
    ADD SYSTEM_LOG_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

ALTER TABLE SYSTEM_LOGS
    ADD CONSTRAINT FK_SYSTEM_LOGS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);