ALTER TABLE TRANSACTION_LOGS DROP CONSTRAINT TRANSACTION_LOGS_PK;

ALTER TABLE TRANSACTION_LOGS DROP COLUMN TRANSACTION_ID;

ALTER TABLE TRANSACTION_LOGS
    ADD TRANSACTION_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

ALTER TABLE TRANSACTION_LOGS ADD CONSTRAINT FK_TRANSACTION_LOGS_FUSER_ID FOREIGN KEY (FROM_USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE TRANSACTION_LOGS ADD CONSTRAINT FK_TRANSACTION_LOGS_TUSER_ID FOREIGN KEY (TO_USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE TRANSACTION_LOGS
    ADD START_TIME DATE NOT NULL;

ALTER TABLE TRANSACTION_LOGS
    ADD FINISH_TIME DATE;

ALTER TABLE TRANSACTION_LOGS
    ADD STATUS VARCHAR(255) NOT NULL;