ALTER TABLE USER_ACTIVITY_LOGS DROP CONSTRAINT USER_ACTIVITY_LOGS_PK;

ALTER TABLE USER_ACTIVITY_LOGS DROP COLUMN ACTIVITY_LOG_ID;

ALTER TABLE USER_ACTIVITY_LOGS
    ADD ACTIVITY_LOG_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

ALTER TABLE USER_ACTIVITY_LOGS
    ADD CONSTRAINT FK_USER_ACTIVITY_LOGS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
